// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/model/account_balance_model.dart';
import 'data/local/model/investment_category_model.dart';
import 'data/local/model/investment_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 8655493933260001259),
      name: 'AccountBalanceModel',
      lastPropertyId: const obx_int.IdUid(4, 7802499258600519140),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3643973412398762034),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3244349508305086520),
            name: 'balance',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7802499258600519140),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5766444206923592438),
      name: 'InvestmentCategoryModel',
      lastPropertyId: const obx_int.IdUid(3, 5076139357253437080),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7697373102988239756),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5076139357253437080),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 1587952917490308533),
      name: 'InvestmentModel',
      lastPropertyId: const obx_int.IdUid(7, 5888586994069415328),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2133601920266520084),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3810698788236716327),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7926085827161714460),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8404021483014432959),
            name: 'averagePrice',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3224617259458797731),
            name: 'quantity',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5888586994069415328),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 7556552766392451763),
            relationTarget: 'InvestmentCategoryModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 1587952917490308533),
      lastIndexId: const obx_int.IdUid(4, 7556552766392451763),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [
        6061803532507860921,
        5578348073718933208,
        7526836149251142061
      ],
      retiredPropertyUids: const [
        5442701740373731167,
        7001073841103006385,
        8010071139626763740
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AccountBalanceModel: obx_int.EntityDefinition<AccountBalanceModel>(
        model: _entities[0],
        toOneRelations: (AccountBalanceModel object) => [],
        toManyRelations: (AccountBalanceModel object) => {},
        getId: (AccountBalanceModel object) => object.id,
        setId: (AccountBalanceModel object, int id) {
          object.id = id;
        },
        objectToFB: (AccountBalanceModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(5);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.balance);
          fbb.addInt64(3, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final balanceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object = AccountBalanceModel(
              id: idParam, name: nameParam, balance: balanceParam);

          return object;
        }),
    InvestmentCategoryModel: obx_int.EntityDefinition<InvestmentCategoryModel>(
        model: _entities[1],
        toOneRelations: (InvestmentCategoryModel object) => [],
        toManyRelations: (InvestmentCategoryModel object) => {},
        getId: (InvestmentCategoryModel object) => object.id,
        setId: (InvestmentCategoryModel object, int id) {
          object.id = id;
        },
        objectToFB: (InvestmentCategoryModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(1, object.id);
          fbb.addOffset(2, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = InvestmentCategoryModel(id: idParam, name: nameParam);

          return object;
        }),
    InvestmentModel: obx_int.EntityDefinition<InvestmentModel>(
        model: _entities[2],
        toOneRelations: (InvestmentModel object) => [object.category],
        toManyRelations: (InvestmentModel object) => {},
        getId: (InvestmentModel object) => object.id,
        setId: (InvestmentModel object, int id) {
          object.id = id;
        },
        objectToFB: (InvestmentModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(8);
          fbb.addInt64(1, object.id);
          fbb.addOffset(2, nameOffset);
          fbb.addFloat64(3, object.price);
          fbb.addFloat64(4, object.averagePrice);
          fbb.addFloat64(5, object.quantity);
          fbb.addInt64(6, object.category.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final priceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final averagePriceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final quantityParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = InvestmentModel(
              id: idParam,
              name: nameParam,
              price: priceParam,
              averagePrice: averagePriceParam,
              quantity: quantityParam);
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.category.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AccountBalanceModel] entity fields to define ObjectBox queries.
class AccountBalanceModel_ {
  /// See [AccountBalanceModel.name].
  static final name =
      obx.QueryStringProperty<AccountBalanceModel>(_entities[0].properties[0]);

  /// See [AccountBalanceModel.balance].
  static final balance =
      obx.QueryDoubleProperty<AccountBalanceModel>(_entities[0].properties[1]);

  /// See [AccountBalanceModel.id].
  static final id =
      obx.QueryIntegerProperty<AccountBalanceModel>(_entities[0].properties[2]);
}

/// [InvestmentCategoryModel] entity fields to define ObjectBox queries.
class InvestmentCategoryModel_ {
  /// See [InvestmentCategoryModel.id].
  static final id = obx.QueryIntegerProperty<InvestmentCategoryModel>(
      _entities[1].properties[0]);

  /// See [InvestmentCategoryModel.name].
  static final name = obx.QueryStringProperty<InvestmentCategoryModel>(
      _entities[1].properties[1]);
}

/// [InvestmentModel] entity fields to define ObjectBox queries.
class InvestmentModel_ {
  /// See [InvestmentModel.id].
  static final id =
      obx.QueryIntegerProperty<InvestmentModel>(_entities[2].properties[0]);

  /// See [InvestmentModel.name].
  static final name =
      obx.QueryStringProperty<InvestmentModel>(_entities[2].properties[1]);

  /// See [InvestmentModel.price].
  static final price =
      obx.QueryDoubleProperty<InvestmentModel>(_entities[2].properties[2]);

  /// See [InvestmentModel.averagePrice].
  static final averagePrice =
      obx.QueryDoubleProperty<InvestmentModel>(_entities[2].properties[3]);

  /// See [InvestmentModel.quantity].
  static final quantity =
      obx.QueryDoubleProperty<InvestmentModel>(_entities[2].properties[4]);

  /// See [InvestmentModel.category].
  static final category =
      obx.QueryRelationToOne<InvestmentModel, InvestmentCategoryModel>(
          _entities[2].properties[5]);
}
